stages:
  - clean	
  - build
  - test
  - document
  - notify

variables:
  ANT_HOME: "/usr/bin/ant"
  PATH_ANT: "$PATH:$ANT_HOME/bin"

  
before_script:
    - apt-get update -y
    - apt-get install -y ant openjdk-17-jdk || { echo "Failed to install Ant"; exit 1; }
    - echo "Ant installation successful. Path:"
    - which ant
    - ant -version  # Verify the Ant installation

  
clean:
  stage: clean
  script:
    - apt-get update -y
    - ant clean

build:
  stage: build
  script:
    - ant compile
  artifacts:
    paths:
      - bin/Tetris.jar

test:
  stage: test
  script:
    - ant test-reports
  artifacts:
    paths:
      - bin/test-results/
      - test-reports/
  dependencies:
    - build

document:
  stage: document
  script:
    - ant javadoc
  artifacts:
    paths:
      - java-doc/
  dependencies:
    - build

notify:
  stage: notify
  script:
    - |
      curl -X POST -H "Content-Type: application/json" \
      -d '{
            "text": "Compilé avec succès"
          }' \
        $NOTIFY_URL https://chat.googleapis.com/v1/spaces/AAAAbRqmWPk/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=oxHNTaC3Byywe-BcH2GYuwsuM_hFnUFdwKVgWqfHoGM
