<?xml version="1.0" encoding="UTF-8"?>

<project name="Compilation de Tetris" default="compile" basedir=".">
  <description>
    Compilation de Tetris avec ant
  </description>
  <property name="src" location="src"/>
  <property name="bin" location="bin"/>
  <property name="libs" location="lib"/>

  <property name="dist" location="dist"/>
  <property name="main-class" location="src/fr/ubo/tetris/Tetris"/>
  <property name="compile.classpath" location="lib/commons-lang3-3.5.jar"/>


  <target name="init">
    <tstamp/>
    <mkdir dir="${bin}"/>
  </target>

  <target name="compile" depends="init"
        description="compile the source">
    <javac srcdir="${src}" destdir="${bin}"/>
  </target>

  <target name="dist" depends="compile"
        description="generate the distribution">
    
    <mkdir dir="${dist}/lib"/>
    <jar jarfile="${dist}/lib/Tetris.jar" basedir="${bin}" Implementation-Version="1.0.1" Main-Class="Tetris" Class-Path="lib/commons-lang3-3.5.jar" Built-By="Mohamed EL HADDAD" />
  </target>

  <target name="clean"
        description="clean up">
        
        <echo message ="Suppression des fichiers issues de la compilation "></echo>
    <delete dir="${dist}"/>
  	<delete dir="${bin}"/>
  </target>
</project>