name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          echo "Building project..."

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./nin/Tetris.jar

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')  
    if :     if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Déploiement vers Docker Hub"
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          
      - name: Tag and Push Docker Image
        run: |
          docker tag tetris-project:latest $DOCKER_USERNAME/tetris-project:${{ github.ref_name }}
          docker push $DOCKER_USERNAME/tetris-project:${{ github.ref_name }}
